language: java
jdk: oraclejdk8
services:
  - postgresql
before_script:
before_script:
  - psql -c "CREATE DATABASE contactholer;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '123';" -U postgres
  - psql -U postgres -d contactholder -a -f contactholder.sql
  - export PGPASSWORD="123"